### ISSUE TITLE
InvalidOperationException

### ISSUE THREAD

**Issue by pmsensi** [porrey/Virtual-ZPL-Printer#14]
**Describe the bug**
When running in debug mode on Visual Studio 2022, an InvalidOperationException occurs with the message:
Unable to resolve service for type 'Diamond.Core.Repository.IRepositoryFactory' while attempting to activate 'VirtualZplPrinter.ViewModels.MainViewModel

**To Reproduce**
1. Open ZPL Printer Solution.sln with Visual Studio 2022
2. Rebuild solution
3. Start in debug mode

**Expected behavior**
The application should start without any error

**Screenshots**
![image](https://user-images.githubusercontent.com/102769589/206561164-860585ca-7c7e-4290-8b10-29d003dccd2a.png)

**Desktop: **
 - OS: Windows 10
 - Visual Studio 2022

**Comment by porrey** [comment]
In each project there is a **Services** folder with JSON files. Mark each file to copy to the build the folder. These define objects that are loaded into the container.

**Comment by pmsensi** [comment]
That was the problem.

Thank you for your fast answer! 

Nice work!
