### ISSUE TITLE
Custom file naming for virtual ZPL printer

### ISSUE THREAD

**Issue by T0mmiB** [porrey/Virtual-ZPL-Printer#21]
Currently, the virtual ZPL printer uses a default file naming convention when saving print jobs as .png files. However, it would be useful to have the ability to pass a custom file name to the virtual printer, so that the generated .png files can be easily identified and organized.

This feature will be useful for applications that need to generate multiple ZPL files with different names.

**Comment by porrey** [comment]
I will consider this enhancement.

**Comment by porrey** [comment]
This feature has been added to version 3.0.1. The base file name can be specified in a ZPL comment using the format

`^FX ImageFileName: USPS-Shipping`

- Only one per ZPL file is used (the first line encountered will be used). 
- Only the base file name can be specified as the application still controls the numbering.
- If an extension is included, it will be ignored.
- Multiple labels within the same ZPL file/transmission will all use the same base name.
