### ISSUE TITLE
Sizes in millimeters or centimeters not saving correctly

### ISSUE THREAD

**Issue by sefirosweb** [porrey/Virtual-ZPL-Printer#29]
**Describe the bug**
When you set the label in millimeters this does not save correctly

**To Reproduce**
1. Go to labels and create new one
2. Select millimeters and save
3. If you close and open again the value is not same has saved
 
![image](https://user-images.githubusercontent.com/20754836/222674486-1b810422-5c79-4958-a974-1f1dc540a6cc.png)

![image](https://user-images.githubusercontent.com/20754836/222674593-81c7c127-6fb8-4580-8e79-7cc062a3ec2b.png)

**Desktop (please complete the following information):**
 - OS: [Windows 11]
![image](https://user-images.githubusercontent.com/20754836/222674781-b068554d-92ec-4ae5-95a9-77dde595ec9c.png)

** In inchs works fine **

**Comment by holliger** [comment]
same problem here...
