### ISSUE TITLE
Labelary service error

### ISSUE THREAD

**Issue by deanopegs** [porrey/Virtual-ZPL-Printer#3]
Hello
Trying some test prints today and I am getting a Labelary service error "Not Found".  Is your application using the labelary API?  There may have been a recent update.  Thanks

**Comment by porrey** [comment]
Yes this uses Labelary. I just tested the latest code as well as the latest installer and I was able to get a label. Perhaps their service was down or offline?

**Comment by justinheilbronfd** [comment]
Hello, same issue on my side. I have tried running as admin and there is nothing showing in event viewer. Running Windows 10 Pro 64bit.

**Comment by porrey** [comment]
Can you provide more details to help troubleshoot?

**Comment by mikolatero** [comment]
Same issue here.

It's only happend when "Label Units" it's changed to 'Centimeter' or 'Milimeter'. With 'Inch' works like a charm.

**Comment by porrey** [comment]
I have updated the code to resolve the 404 issue when selecting MM or CM. The issue was caused by too many decimal points in the URL after converting the values to inches. The URL is formatted to use two decimal points. Version 1.0.12 is the latest version. The installer has been updated as well. Please let me know if this resolves your specific issue(s).

**Comment by porrey** [comment]
Closed due to no further activity.

**Comment by ASTIN-UA** [comment]
Hi. Grate thank for this app! But I have same error. If use SM or MM. And same error if I use on Inch for example 0.7 or 1.5 Inch.

**Comment by porrey** [comment]
I am unable to reproduce the issue. It would be helpful if you could outline the steps to reproduce the issue (I may be missing  something very simple). I'll fix the issue as soon as I can identify it. Thanks.

**Comment by jhubsharp** [comment]
Hi there, I'm seeing a similar problem using the Virtual ZPL printer from the installer (version 1.0.12). I'm running this through Zebra's Browser Print Service (https://www.zebra.com/us/en/products/software/barcode-printers/link-os/browser-print.html). The Virtual ZPL printer is configured in Zebra's tool, but when I try to print a label, I get an error from BrowserPrint and when I check Virtual ZPL Printer I see the "Labelary Service Error". 

The printer is configured to 127.0.0.1:5900 with 4x6 inches and 8dpmm if any of that helps. I haven't tried going into the source yet but that's my next stop.

**Comment by jhubsharp** [comment]
Running the source, it looks like a 404 is coming back from Labelary.

**Comment by porrey** [comment]
Thanks. Can you post the "bad" ZPL you used here so I can test/reproduce the issue?

**Comment by porrey** [comment]
I ran the following test:
1) I installed the application from the latest MSI
2) I edited the `**Samples/6x4-203dpi.txt**` file in the install folder by removing a large portion of the text to. are the ZPL invalid
3) started the Virtual ZPL printer and clicked **Test**

Here is the result:

<img width="586" alt="V-404" src="https://user-images.githubusercontent.com/12475115/157361608-265b3d99-2262-40ad-8941-c1030d5ad5ba.png">
.

**Comment by porrey** [comment]
Updated:

<img width="646" alt="Screen Shot 2022-03-08 at 9 09 50 PM" src="https://user-images.githubusercontent.com/12475115/157365357-4ae92cf6-fb14-4fca-a9f4-e22a2c2918f4.png">

**Comment by jhubsharp** [comment]
Hi, it actually wasn't ZPL, it was a Zebra printer function command (~HQES) to get printer status. Looks like this code is doing a health check on the printer before sending the ZPL. Sending that to Labelary fails to return a label as expected so the behavior is all correct from the printer side.

That said, I think the message above is clearer and probably would have pointed me in the right direction sooner.
