### ISSUE TITLE
Test windows not working propelly (can't paste or add enters)

### ISSUE THREAD

**Issue by sefirosweb** [porrey/Virtual-ZPL-Printer#30]
**Describe the bug**
If you are using a test windows they seems block some actions,

Can't paste a custom ZPL code, also can't add new lines, the "enter" button seems locked

**To Reproduce**
1. Click on test
2. Write new lines with enter it dosent works
3. Or you want to pase code with CTRL + V

![image](https://user-images.githubusercontent.com/20754836/222678428-7e1c918d-7af7-43dd-bf4b-a791d8ab6566.png)

![image](https://user-images.githubusercontent.com/20754836/222678489-4d778ea0-f020-4e93-ad53-b001535ecbe5.png)

**Comment by IcuScc** [comment]
I have he same problem.

**Comment by porrey** [comment]
Fixed is latest release. Please confirm and close issue if resolved.
