### ISSUE TITLE
Print settings takes into account regional formatting

### ISSUE THREAD

**Issue by eherralaette** [porrey/Virtual-ZPL-Printer#33]
When editing printer configuration and setting the Label Height/Width settings, the program takes into account the system locale regional format settings. 

So if the windows regional format uses comma as a decimal separator, it will only allow to enter Label Height/Width with a comma.

So label height 4,5 instead of 4.5.

The program then uses the value with a comma in the API URL it sends Labelary and comes back with a 404 response.

**To Reproduce**
1. Go to "Additional date, time & regional settings" in Windows control panel
2. In "Formats" tab, go to "Additional Settings..."
3. For "Decimal symbol" enter a comma.
4. Press OK
5. Open Virtual ZPL Printer
6. Edit Active Printer Configuration
7. Enter Label Height or Label Width with a decimal number (example: 2,5)
8. Save
9. Press Start
10. Press Test and send

**Expected behavior**

A valid print label.

**Screenshots**

![image](https://github.com/porrey/Virtual-ZPL-Printer/assets/136076484/78a5c8d8-c9cd-418d-ab6a-4ec6c2698f5f)

![image](https://github.com/porrey/Virtual-ZPL-Printer/assets/136076484/233b0d69-20b7-421c-ad03-3c18b4d166dc)

**Desktop (please complete the following information):**
 - OS: Windows 10 Ultimate

**Comment by porrey** [comment]
Fixed is latest release. Please confirm and close issue if resolved.
