### ISSUE TITLE
Save as PDF

### ISSUE THREAD

**Issue by Zoenchen** [porrey/Virtual-ZPL-Printer#35]
Is it possible to save the output as PDF instead of PNG?

**Comment by porrey** [comment]
This would add complexity to the UI. For example, the UI references the PNG directly from the cache folder. It may be possible to add a PDF along side the PNG with the same name. Would this feature be helpful?

**Comment by Zoenchen** [comment]
I think this would be helpful, but I already solved my problem by another way.
Thank you.
