### ISSUE TITLE
Print ZPL Bug

### ISSUE THREAD

**Issue by JorgelGtzGtz** [porrey/Virtual-ZPL-Printer#38]
Hello, 

The application sent an error when trying to print one ZPL 

![image](https://github.com/porrey/Virtual-ZPL-Printer/assets/37045031/cf96edfb-e7be-48ac-9c60-e1899781d032)

but in another viewer is working fine

![image](https://github.com/porrey/Virtual-ZPL-Printer/assets/37045031/8b859cea-daa9-4d7c-8d6a-ac7041a97712)

this is the ZPL

[ZPLSample.txt](https://github.com/porrey/Virtual-ZPL-Printer/files/12561988/ZPLSample.txt)

Exist a log for checking the issue ?

Thanks

**Comment by Yacinezaz** [comment]
I'm facing the same issue

**Comment by porrey** [comment]
Fixed is latest release. Please confirm and close issue if resolved.

**Comment by maheshambati410** [comment]
@porrey We are getting same error with latest version (v 3.2.1). 

![image](https://github.com/porrey/Virtual-ZPL-Printer/assets/40993969/1dd1019f-4cb2-49c8-a4db-93b36bd9f38d)

**Comment by porrey** [comment]
This ticket was closed for two reasons: 1) based on the details and the ZPL provided, I confirmed this was fixed 2) inactivity/ no response.

Please create a new issue and provide enough details, including any windows settings such as language or region and one or more ZPL samples.

**Comment by jnalley20** [comment]
When sending ZPL from a slow client device, it doesn't always make it to the server while in the stream read loop.  I was able to solve my issue by hard coding a delay.
namespace VirtualPrinter.HostedService.TcpSystem
This was what I changed starting on line 102:

					int numBytesRead = await stream.ReadAsync(data);
					await Task.Run(() => ms.Write(data, 0, numBytesRead));
					await Task.Delay(150);
					this.Logger.LogInformation("{count} byte(s) were read from the incoming connection.", numBytesRead);

					while (stream.DataAvailable && numBytesRead > 0)
					{
						numBytesRead = await stream.ReadAsync(data);
						await Task.Run(() => ms.Write(data, 0, numBytesRead));
						await Task.Delay(150);
						this.Logger.LogInformation("{count} additional byte(s) were read from the incoming connection.", numBytesRead);
					}
