### ISSUE TITLE
404 Error when printing test label ?

### ISSUE THREAD

**Issue by Simon-Syd** [porrey/Virtual-ZPL-Printer#48]
Hello,

thank you very much for your software !
I just installed the lastest version and I have a 404 when testing the label ?
maybe we are not able to contact the labellary api ?

Kind regards,

Simon Poidevin

**Comment by StefanZ09** [comment]
Hello everyone - I have the same problem. It doesn`t matter which printer configuration, which label sizes or resolutions I try, and it also doesn`t matter which test label I use, I always get the 'Labelary Error - ERROR: HTTP 404 Not Found' error. I also tested to send ZPL code from the ERP system (D365 SCM) to the virtual ZPL printer, but with the same error message. I use the version 2.3.0. Any help is very welcome!

**Comment by porrey** [comment]
Earlier versions had bugs that caused invalid URL's to be formed resulting in 404 errors. Please use the latest version to rule out bugs as the source of the issue.

I uploaded version 3.0.2 that contains anew menu option to test Labelary connectivity.

<img width="828" alt="Screenshot 2024-02-01 at 9 24 06 PM" src="https://github.com/porrey/Virtual-ZPL-Printer/assets/12475115/485f7e81-b1ad-4eca-af02-c178aee0825d">

**Comment by StefanZ09** [comment]
Hi Daniel! Thanks a lot for your reply. I talked to my IT-department and ask for help. So they updated the Version of the Virtual ZPL-Printer to Version 3.0.2. They also updated the .net as you described on github. Then I restarted my computer and tried it again, but with the same 404 error message (with test from the ERP system to the printer). Then I tried to use the 'Test label' function within the Virtual ZPL printer but without success. I always get the 'HTTP 404 Not found' error, no matter which 'Test Label' settings I use (4x6 USPS, 2x2 Product label, 4x6 Shipping label). Can you give me another tip what I can do to solve that problem?

**Comment by porrey** [comment]
Can you post a screenshot of the test results?

**Comment by Simon-Syd** [comment]
hello Daniel,
with 3.0.2 it's still KO (404 error when testing)
but the weird thing its that "test labelary" looks fine : 
![image](https://github.com/porrey/Virtual-ZPL-Printer/assets/60176428/7bc52457-84a5-4f1c-8f3c-27201f5da5ea)

another weird thing, when I compare the "test labelary" output from my computer (which is OK) and the other computer, it's the same informations but not in the same order ?
![image](https://github.com/porrey/Virtual-ZPL-Printer/assets/60176428/b2ac41f6-8e09-412a-934b-9e650d0b5968)

just a little text to change here (it's edit instead of test) :
![image](https://github.com/porrey/Virtual-ZPL-Printer/assets/60176428/18dca6dc-4657-483f-814a-d548ff07ecea)

thanks for your help

**Comment by Simon-Syd** [comment]
we had to remove this file after uninstalling the software : 
![image](https://github.com/porrey/Virtual-ZPL-Printer/assets/60176428/ae1df879-8203-4471-89c8-41000c316132)
not it's fine !

**Comment by CMIGIT** [comment]
It seems to be with and height in the url to labelary, because in some PC, the decimal separator is "," (coma) and not a point "."

**Comment by CMIGIT** [comment]
In :
Virtual-ZPL-Printer\Src\Virtual Printer Solution\Labelary.Service\LabelService.cs

After (line 110)
```
						if (width <= 15 && height <= 15)
						{
							string url = $"{this.LabelServiceConfiguration.BaseUrl}/{labelConfiguration.Dpmm}dpmm/labels/{width:#.##}x{height:#.##}/{labelIndex}/";
							url = url.Replace(",", "."); // Add this : Violent but normally no comma in url so complete replacement
```

**Comment by porrey** [comment]
Is your system local set to use a comma for decimal separator?

**Comment by porrey** [comment]
The latest release forces US English when formatting the label sizes for the Labelary API.

**Comment by CMIGIT** [comment]
I'm already have th issue.
Here is a possible correction, with your code

							```
CultureInfo v_CultureInfo = CultureInfo.InstalledUICulture;
							NumberFormatInfo v_NumberFormatInfoPoint = (NumberFormatInfo)v_CultureInfo.NumberFormat.Clone();
							v_NumberFormatInfoPoint.NumberDecimalSeparator = ".";

							string widthString = width.ToString("#.##", v_NumberFormatInfoPoint);
							this.Logger.LogDebug("The Width parameter is '{value}'.", widthString);
							string heightString = height.ToString("#.##", v_NumberFormatInfoPoint);
							this.Logger.LogDebug("The Height parameter is '{value}'.", heightString);
```

**Comment by porrey** [comment]
Please describe the issue and open a new error.

**Comment by CMIGIT** [comment]
I still have the same issue. 
height and width always have commas when transforming to string.
I propose this code to correct, to force decimal separator.
Note that you can set "v_NumberFormatInfoPoint" in static and compute only once.

**Comment by porrey** [comment]
I need to be able to reproduce the issue to correct it properly. I have no way of ensuring the code change corrects the issue . Please provide enough details to reproduce the issue.

**Comment by porrey** [comment]
One of the tests I ran was to change my configuration for us-EN the same as above and I get proper operation. Can you provide more information such as what other language are you running, which one is primary? Also, is the log generating? Can you attach the log file?

**Comment by CMIGIT** [comment]
May be you can reproduce the issue if you change your regional settings to set comma in decimal separator and space for thousand separator.
Then you  configure the printer with paper in centimeters, and setsize to 10cm x 15cm.
You should see, that height and width after convert in string have comma and not point ;-)

**Comment by porrey** [comment]
That is the test I ran before publishing.

**Comment by ASTIN-UA** [comment]
Good afternoon. I have the same problem. I set the size in millimeters. 25х40. The label is not displayed, moreover, the program crashes. The localization is Ukrainian. If you convert the entered millimeters to inches, you get the following:
 ![image](https://github.com/porrey/Virtual-ZPL-Printer/assets/17588757/cd8ee00b-b044-4f57-9f45-006774e50412) 
And, accordingly, the print does not go. The output image is of the following type:
 ![image](https://github.com/porrey/Virtual-ZPL-Printer/assets/17588757/17f80bcc-bd7a-471e-a140-1be8a3cb196f) 
If you convert the settings to inches and align to an integer, it starts working.
OS: win 11
locale: Ukrainian
If you need some logs, say me whare can i find it.

**Comment by ASTIN-UA** [comment]
THK! in 3.2.0 no more this problem! But crush...

**Comment by CMIGIT** [comment]
It's ok with 3.2.1
