### ISSUE TITLE
VZPL crush after printing

### ISSUE THREAD

**Issue by ASTIN-UA** [porrey/Virtual-ZPL-Printer#51]
THK you for your soft! 
But it crush every time after printing...
v 3.2.0
Win 11
I print with this code:

> ^XA
> ^LH0,0
> ^CI28
> ^FO10,20^A0N,25,20^FDСеча (Стерильний контейнер)^FS
> ^FO10,45^A0N,25,20^FDЛубніна жін. 07.10.1984^FS
> ^FO10,70^A0N,20,18^FDКсенія Макарівна^FS
> ^BY2,3,40
> ^FO60,100^BCN,50,N,N,N,A^FD002463^FS
> ^FO95,160^A0N30,20^FD002463 ^FS
> ^XZ

or any other text on this code.... 
No information about crash in logs, but I add it.
[Virtual-ZPL-Printer-Log202402180032.txt](https://github.com/porrey/Virtual-ZPL-Printer/files/14320399/Virtual-ZPL-Printer-Log202402180032.txt)

In addition, there is an error in the program window after launch:
![image](https://github.com/porrey/Virtual-ZPL-Printer/assets/17588757/0c5348c8-e65a-4b99-867d-7d8edc33355e)

Thank you in advance for solving the problem!

**Comment by ASTIN-UA** [comment]
If you need, I can add video with problem, any tests, any files...

**Comment by porrey** [comment]
Did this work before? I use Humanizer and it appears this may be lacking support for a specific language. Any information you can provide would be helpful.

**Comment by ASTIN-UA** [comment]
I think this mistake has been made before. However, does it affect the program's performance? It allows you to print a few labels, then freezes, and then just closes...

**Comment by ASTIN-UA** [comment]
I use Ukrainian language, but it can be russian or any other...

**Comment by ASTIN-UA** [comment]
I wrote about this in my application https://github.com/porrey/Virtual-ZPL-Printer/issues/48
The program crashed before, and I didn't have much time to write a bug report.

**Comment by porrey** [comment]
Try this test version. The install is at https://github.com/porrey/Virtual-ZPL-Printer/blob/main/Installer/Virtual%20ZPL%20Printer%20Setup-3.2.1.msi. 

1. Wrapped the Humanizer code in a try/catch with default formatting when the language is not found.
2. Added all available languages for Humazinzer

> Note: You will need to uninstall this version before installing the next official release.

**Comment by ASTIN-UA** [comment]
Yay! Everything works! The program doesn't crash! Everything seems to be OK! Moreover, on the preview of labels began to write in Ukrainian!

![image](https://github.com/porrey/Virtual-ZPL-Printer/assets/17588757/fa8564e3-8a7d-49fe-b09a-cea19e6bddd4)

There are still a couple of questions, but this is already in some variant of personal communication or a new ticket! Thank you very much, I think it can be released).

P.S.: Please consider my ticket on the new functionality. Thanks in advance!

**Comment by porrey** [comment]
Thanks for responding.
