### ISSUE TITLE
Printer error on zpl with images

### ISSUE THREAD

**Issue by sanjuleo** [porrey/Virtual-ZPL-Printer#67]
Printer is not taking complete input when there are images used in zpl. The error says "You requested the 1st label, but the specified ZPL doesn't generate any labels.
Same zpl is working fine with the Labelary online viewer.

![image](https://github.com/user-attachments/assets/1f3e60c1-23fc-47f3-8010-e5a8849c7417)

**Comment by porrey** [comment]
Please send me a ZPL that is failing. Also, please try with the latest posted version.

**Comment by porrey** [comment]
Here is the output from that ZPL in the latest version.

<img width="678" alt="Screenshot 2024-09-10 at 6 18 12 PM" src="https://github.com/user-attachments/assets/80840fa3-4313-4450-8b11-daf5bf726e94">

I built the installer on my MacBook Pro M1 and it defaulted to ARM. I have uploaded a new version of the installer.

**Comment by sanjuleo** [comment]
Thanks, new installer is working fine.

**Comment by sanjuleo** [comment]
Issue is fixed
